In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [2]:
my_data = pd.read_csv("/Users/nguyenducthien/Downloads/Code/Visual Studio Code/training/data/drug200.csv")
my_data[0:5]

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [3]:
my_data.shape

(200, 6)

In [4]:
X = my_data.drop(columns=['Drug'])
y = my_data[['Drug']]

In [5]:
'''od = OrdinalEncoder(categories=[['F','M'],['LOW','NORMAL','HIGH'],['LOW','NORMAL','HIGH']])
X[['Sex','BP','Cholesterol']] = od.fit_transform(X[['Sex','BP','Cholesterol']])
scaler = StandardScaler()
X[['Na_to_K']] = scaler.fit_transform(X[['Na_to_K']])
X'''

"od = OrdinalEncoder(categories=[['F','M'],['LOW','NORMAL','HIGH'],['LOW','NORMAL','HIGH']])\nX[['Sex','BP','Cholesterol']] = od.fit_transform(X[['Sex','BP','Cholesterol']])\nscaler = StandardScaler()\nX[['Na_to_K']] = scaler.fit_transform(X[['Na_to_K']])\nX"

In [6]:
ct = ColumnTransformer(
    transformers=[
        ('Sex',OrdinalEncoder(categories=[['F','M']]),['Sex']),
        ('BP', OrdinalEncoder(categories=[['LOW','NORMAL','HIGH']]),['BP']),
        ('Cholesterol',OrdinalEncoder(categories=[['LOW','NORMAL','HIGH']]),['Cholesterol']),
        ('Na_to_K', StandardScaler(),['Na_to_K'])
    ], remainder='passthrough'
)
X = ct.fit_transform(X)

In [7]:
le = LabelEncoder()
y = pd.DataFrame(le.fit_transform(y),columns=['Drug'])
y

/Users/nguyenducthien/miniconda3/envs/ml/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

     Drug
0       4
1       2
2       2
3       3
4       4
..    ...
195     2
196     2
197     3
198     3
199     3

[200 rows x 1 columns]